-- Retire `users.license_number` for real: drop the column, do not freeze it.
--
-- The backfill already seeded one `inspector_credentials` row per licensed
-- user (`sort_order = -1`), and every renderer now reads
-- `CredentialService.primaryLicenseNumber`. Nothing reads or writes this
-- column, so a frozen-but-present column is only a name people will trip over.
-- Pre-launch, there is no downstream consumer to keep compatible.
--
-- WHY A BARE `DROP COLUMN` AND NOT A GENERATED MIGRATION
--
-- `users` is the FK target of six tables (inspection.inspector_id,
-- inspector_assignments, agreements.inspector_user_id, automation rules,
-- integration credentials). The hazard this repository has actually been
-- bitten by is drizzle's 12-step rebuild — CREATE __new_users / INSERT /
-- DROP TABLE users / RENAME — because that `DROP TABLE` on an FK-referenced
-- table is what loses rows on remote D1.
--
-- SQLite's native `ALTER TABLE … DROP COLUMN` is not a rebuild: the table
-- keeps its identity, so no FK is ever dangling and no data is copied. It is
-- refused only when the column carries an index, a UNIQUE/PK constraint, a
-- CHECK, or a view/trigger reference. `license_number` is a plain nullable
-- TEXT with none of those (verified against `0000_baseline.sql` and every
-- forward migration), which is exactly the case the native form handles.
--
-- Hand-written rather than generated for that reason: the statement that runs
-- must be this one, and a regenerated file could silently become the rebuild.
ALTER TABLE `users` DROP COLUMN `license_number`;
