import {
  type RouteConfig,
  index,
  route,
  layout,
} from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  // Full-screen editor (own chrome, no sidebar)
  route("inspections/:id/edit", "routes/inspection-edit.tsx"),
  route("templates/:id/edit", "routes/template-edit.tsx"),
  // Public pages — no auth, minimal layout, SSR for SEO
  layout("routes/public-layout.tsx", [
    route("book/:tenant/:slug", "routes/public/booking.tsx"),
    route("report/:tenant/:id", "routes/public/report.tsx"),
    route(
      "agreements/sign/:tenant/:token",
      "routes/public/agreement-sign.tsx",
    ),
    route("r/:id/invoice", "routes/public/invoice.tsx"),
    route("verify/:envelopeId", "routes/public/verify.tsx"),
    route("observe/inspections/:id", "routes/public/observe.tsx"),
  ]),
  // Error / utility pages (bare, outside auth)
  route("not-found", "routes/not-found.tsx"),
  route("feature-disabled", "routes/feature-disabled.tsx"),
  layout("routes/auth-layout.tsx", [
    route("dashboard", "routes/dashboard.tsx"),
    route("calendar", "routes/calendar.tsx"),
    route("contacts", "routes/contacts.tsx"),
    route("invoices", "routes/invoices.tsx"),
    route("notifications", "routes/notifications.tsx"),
    route("templates", "routes/templates.tsx"),
    route("team", "routes/team.tsx"),
    route("metrics", "routes/metrics.tsx"),
    route("apprentice-review", "routes/apprentice-review.tsx"),
    route("reports", "routes/reports.tsx"),
    layout("routes/settings-layout.tsx", [
      route("settings", "routes/settings-hub.tsx"),
      route("settings/profile", "routes/settings-profile.tsx"),
      route("settings/workspace", "routes/settings-workspace.tsx"),
      route("settings/services", "routes/settings-services.tsx"),
      route("settings/communication", "routes/settings-communication.tsx"),
      route("settings/automations", "routes/settings-automations.tsx"),
      route("settings/data", "routes/settings-data.tsx"),
      route("settings/widget", "routes/settings-widget.tsx"),
      route("settings/account", "routes/settings-account.tsx"),
      route("settings/advanced", "routes/settings-advanced.tsx"),
      route("settings/integrations", "routes/settings-integrations.tsx"),
      route("settings/integrations/qbo", "routes/settings-integrations-qbo.tsx"),
      route("settings/event-types", "routes/settings-event-types.tsx"),
      route("settings/inspection-types", "routes/settings-inspection-types.tsx"),
      route("settings/catalog/booking", "routes/settings-catalog-booking.tsx"),
      route("settings/billing", "routes/settings-billing.tsx"),
      route("settings/security", "routes/settings-security.tsx"),
    ]),
    route("comments", "routes/comments.tsx"),
    route("recommendations", "routes/recommendations.tsx"),
    route("library/tags", "routes/library/tags.tsx"),
    route("agreements", "routes/agreements.tsx"),
    route("library/rating-systems", "routes/library/rating-systems.tsx"),
    route("marketplace", "routes/marketplace.tsx"),
  ]),
  layout("routes/agent-layout.tsx", [
    route("agent-dashboard", "routes/agent/dashboard.tsx"),
    route("agent-settings/profile", "routes/agent/settings-profile.tsx"),
    route("agent-inspectors", "routes/agent/inspectors.tsx"),
    route("agent-recommendations", "routes/agent/recommendations.tsx"),
  ]),
] satisfies RouteConfig;
